// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://joxdblsmudzqetaiqhdl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpveGRibHNtdWR6cWV0YWlxaGRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIxOTE0NDAsImV4cCI6MjA4Nzc2NzQ0MH0.zKUc4Hj7Q_iW0bHBbBNo384MlU55lugHtF4DzOtOJLE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});